# Generated by Django 5.1.7 on 2025-05-30 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('comun', '0001_initial'),
        ('establecimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppkioskoPromociones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_descuento', models.IntegerField()),
                ('fecha_inicio_promo', models.DateTimeField()),
                ('fecha_fin_promo', models.DateTimeField(blank=True, null=True)),
                ('tipo_promocion', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_promocional', models.CharField(blank=True, max_length=50, null=True)),
                ('limite_uso_usuario', models.IntegerField(blank=True, null=True)),
                ('limite_uso_total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.appkioskoestados')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'appkiosko_promociones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPublicidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_publicidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_inicio_publicidad', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_publicidad', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.appkioskoestados')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.appkioskopromociones')),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Publicidades',
                'db_table': 'appkiosko_publicidades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=500)),
                ('duracion', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('publicidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.appkioskopublicidades')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'appkiosko_video',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPromocionmenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.appkioskomenus')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.appkioskopromociones')),
            ],
            options={
                'verbose_name': 'Promoción Menú',
                'verbose_name_plural': 'Promociones Menús',
                'db_table': 'appkiosko_promocionmenu',
                'managed': True,
                'unique_together': {('menu', 'promocion')},
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPromocionproductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.appkioskoproductos')),
                ('promocion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.appkioskopromociones')),
            ],
            options={
                'verbose_name': 'Promoción Producto',
                'verbose_name_plural': 'Promociones Productos',
                'db_table': 'appkiosko_promocionproductos',
                'managed': True,
                'unique_together': {('producto', 'promocion')},
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPublicidadestablecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimientos.appkioskoestablecimientos')),
                ('publicidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.appkioskopublicidades')),
            ],
            options={
                'verbose_name': 'Publicidad Establecimiento',
                'verbose_name_plural': 'Publicidades Establecimiento',
                'db_table': 'appkiosko_publicidadestablecimiento',
                'managed': True,
                'unique_together': {('establecimiento', 'publicidad')},
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPublicidadkioskotouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('kiosko_touch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimientos.appkioskokioskostouch')),
                ('publicidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.appkioskopublicidades')),
            ],
            options={
                'verbose_name': 'Publicidad Kiosko',
                'verbose_name_plural': 'Publicidades Kiosko',
                'db_table': 'appkiosko_publicidadkioskotouch',
                'managed': True,
                'unique_together': {('kiosko_touch', 'publicidad')},
            },
        ),
    ]
