# Generated by Django 5.1.7 on 2025-05-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppkioskoCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_creacioncupon', models.DateTimeField(blank=True, db_column='fecha_creacionCupon', null=True)),
                ('fecha_fincupon', models.DateTimeField(blank=True, db_column='fecha_finCupon', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cupón',
                'verbose_name_plural': 'Cupones',
                'db_table': 'appkiosko_cupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=500)),
                ('categoria_imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_referencial_imagen', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Imagen de Publicidad',
                'verbose_name_plural': 'Imágenes de Publicidad',
                'db_table': 'appkiosko_imagen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPromocioncategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Promoción por Categoría',
                'db_table': 'appkiosko_promocioncategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPromociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_descuento', models.IntegerField()),
                ('fecha_iniciopromo', models.DateTimeField(db_column='fecha_inicioPromo')),
                ('fecha_finpromo', models.DateTimeField(blank=True, db_column='fecha_finPromo', null=True)),
                ('tipo_promocion', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_promocional', models.CharField(blank=True, max_length=50, null=True)),
                ('limite_uso_usuario', models.IntegerField(blank=True, null=True)),
                ('aplicable_a', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_uso_total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'appkiosko_promociones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPromocionmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Promoción por Menú',
                'db_table': 'appkiosko_promocionmenu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPromocionproductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Promoción por Producto',
                'db_table': 'appkiosko_promocionproductos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPublicidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_publicidad', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_or_video_url', models.CharField(blank=True, db_column='imagen_or_video_URL', max_length=500, null=True)),
                ('fecha_iniciopublicidad', models.DateTimeField(blank=True, db_column='fecha_inicioPublicidad', null=True)),
                ('fecha_finpublicidad', models.DateTimeField(blank=True, db_column='fecha_finPublicidad', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Publicidades',
                'db_table': 'appkiosko_publicidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPublicidadestablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Publicidad por Establecimiento',
                'db_table': 'appkiosko_publicidadestablecimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPublicidadkioskotouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Publicidad por Kiosko',
                'db_table': 'appkiosko_publicidadkioskotouch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=500)),
                ('duracion', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video de Publicidad',
                'verbose_name_plural': 'Videos de Publicidad',
                'db_table': 'appkiosko_video',
                'managed': False,
            },
        ),
    ]
