# Generated by Django 5.1.7 on 2025-06-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskopublicidades',
            name='tiempo_visualizacion',
            field=models.PositiveIntegerField(default=5, help_text='Tiempo de visualización en segundos'),
        ),
        migrations.AlterField(
            model_name='appkioskopublicidades',
            name='tipo_publicidad',
            field=models.CharField(choices=[('banner', 'Banner'), ('video', 'Video')], default='banner', help_text='Tipo de publicidad a mostrar', max_length=100),
        ),
    ]
