# Generated by Django 5.1.7 on 2025-06-13 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_appkioskomenuproductos_unique_together_and_more'),
        ('marketing', '0002_appkioskopublicidades_tiempo_visualizacion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appkioskopromocionproductos',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appkioskopromocionproductos',
            name='tamano',
            field=models.ForeignKey(blank=True, help_text='Tamaño específico del producto en esta promoción (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.appkioskotamanos'),
        ),
        migrations.AlterUniqueTogether(
            name='appkioskopromocionproductos',
            unique_together={('producto', 'promocion', 'tamano')},
        ),
    ]
