# Generated by Django 5.1.7 on 2025-07-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_appkioskopromocionproductos_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskopublicidades',
            name='seccion',
            field=models.CharField(choices=[('home', 'Página Principal'), ('menu', 'Menú de Productos'), ('carrito', 'Carrito de Compras'), ('pago', 'Proceso de Pago'), ('turno', 'Sala de Espera/Turno'), ('global', 'Todas las Secciones')], default='global', help_text='Sección del sistema donde se mostrará la publicidad', max_length=50),
        ),
    ]
