# Generated by Django 5.1.7 on 2025-05-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppkioskoDetallefacturaproducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(db_column='IVA', decimal_places=2, max_digits=5)),
                ('descuento', models.DecimalField(blank=True, db_column='DESCUENTO', decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emisionfactura', models.DateTimeField(db_column='fecha_emisionFactura')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'db_table': 'appkiosko_detallefacturaproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoFacturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula_cliente', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'appkiosko_facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('tipo_entrega', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_mesa', models.IntegerField(blank=True, null=True)),
                ('valor_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('is_facturado', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'appkiosko_pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPedidosessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_iniciopedido', models.DateTimeField(db_column='fecha_inicioPedido')),
                ('fecha_finpedido', models.DateTimeField(blank=True, db_column='fecha_finPedido', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sesión de Pedido',
                'verbose_name_plural': 'Sesiones de Pedido',
                'db_table': 'appkiosko_pedidosessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPedidosproductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Producto de Pedido',
                'verbose_name_plural': 'Productos de Pedido',
                'db_table': 'appkiosko_pedidosproductos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoTipopago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pago',
                'db_table': 'appkiosko_tipopago',
                'managed': False,
            },
        ),
    ]
