# Generated by Django 5.1.7 on 2025-06-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appkioskopedidoproductoingredientes',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='appkioskopedidoproductoingredientes',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
