# Generated by Django 5.1.7 on 2025-05-25 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_add_personalizaciones'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appkioskodetallefacturaproducto',
            options={'managed': True, 'verbose_name': 'Detalle de Factura', 'verbose_name_plural': 'Detalles de Factura'},
        ),
        migrations.AlterModelOptions(
            name='appkioskopedidosproductos',
            options={'managed': True, 'verbose_name': 'Producto de Pedido', 'verbose_name_plural': 'Productos de Pedido'},
        ),
        migrations.CreateModel(
            name='AppkioskoPedidoproductoingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('quitar', 'Quitar'), ('añadir', 'Añadir')], max_length=10)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario_ingrediente', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('precio_total_ingrediente', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.appkioskoingredientes')),
                ('pedido_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalizaciones', to='ventas.appkioskopedidosproductos')),
            ],
            options={
                'verbose_name': 'Personalización de Ingrediente',
                'verbose_name_plural': 'Personalizaciones de Ingredientes',
                'db_table': 'appkiosko_pedido_producto_ingredientes',
                'managed': True,
                'unique_together': {('pedido_producto', 'ingrediente')},
            },
        ),
        migrations.RunSQL(
            """
            ALTER TABLE appkiosko_pedido_producto_ingredientes MODIFY COLUMN ingrediente_id INT(11) NOT NULL;
            ALTER TABLE appkiosko_pedido_producto_ingredientes MODIFY COLUMN pedido_producto_id INT(11) NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE appkiosko_pedido_producto_ingredientes MODIFY COLUMN ingrediente_id BIGINT(20) NOT NULL;
            ALTER TABLE appkiosko_pedido_producto_ingredientes MODIFY COLUMN pedido_producto_id BIGINT(20) NOT NULL;
            """
        ),
    ]
