# Generated by Django 5.1.7 on 2025-06-27 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_appkioskopromocionproductos_unique_together_and_more'),
        ('ventas', '0002_alter_appkioskopedidoproductoingredientes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskodetallepedido',
            name='descuento_promocion',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Descuento aplicado por la promoción', max_digits=10),
        ),
        migrations.AddField(
            model_name='appkioskodetallepedido',
            name='precio_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio antes de aplicar promoción', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='appkioskodetallepedido',
            name='promocion',
            field=models.ForeignKey(blank=True, help_text='Promoción aplicada a este producto/menú', null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.appkioskopromociones'),
        ),
    ]
