# Generated by Django 5.1.7 on 2025-08-04 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_alter_appkioskoingredientes_categoria_producto_and_more'),
        ('ventas', '0003_appkioskodetallepedido_descuento_promocion_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appkioskopedidoproductoingredientes',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appkioskopedidoproductoingredientes',
            name='detalle_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.appkioskodetallepedido'),
        ),
        migrations.AlterUniqueTogether(
            name='appkioskopedidoproductoingredientes',
            unique_together={('pedido', 'detalle_pedido', 'ingrediente', 'accion')},
        ),
    ]
