# Generated by Django 5.1.7 on 2025-08-04 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_appkioskopedidoproductoingredientes_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appkioskodetallefacturaproducto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appkioskodetallefacturaproducto',
            name='detalle_pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.appkioskodetallepedido'),
        ),
        migrations.AlterUniqueTogether(
            name='appkioskodetallefacturaproducto',
            unique_together={('factura', 'detalle_pedido')},
        ),
    ]
