# Generated by Django 5.1.7 on 2025-08-08 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_alter_appkioskoingredientes_categoria_producto_and_more'),
        ('ventas', '0005_alter_appkioskodetallefacturaproducto_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskodetallefacturaproducto',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.appkioskomenus'),
        ),
    ]
