# Generated by Django 5.1.7 on 2025-05-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskoingredientes',
            name='categoria_producto',
            field=models.CharField(choices=[('hamburguesas', 'Hamburguesas'), ('pizzas', 'Pizzas'), ('ensaladas', 'Ensaladas'), ('pollo', 'Pollo'), ('postres', 'Postres'), ('bebidas', 'Bebidas'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='appkioskoingredientes',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
