# Generated by Django 5.1.7 on 2025-05-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_appkioskocategorias_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appkioskocategorias',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appkioskocategorias',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
