# Generated by Django 5.1.7 on 2025-06-12 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_appkioskoingredientes_categoria_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppkioskoTamanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Tamaño',
                'verbose_name_plural': 'Tamaños',
                'db_table': 'appkiosko_tamanos',
                'ordering': ['orden', 'nombre'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='appkioskoproductos',
            name='aplica_tamanos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appkioskoproductos',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='productos', through='catalogo.AppkioskoProductosIngredientes', to='catalogo.appkioskoingredientes'),
        ),
        migrations.CreateModel(
            name='AppkioskoProductoTamanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.appkioskoproductos')),
                ('tamano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.appkioskotamanos')),
            ],
            options={
                'verbose_name': 'Precio por Tamaño',
                'verbose_name_plural': 'Precios por Tamaño',
                'db_table': 'appkiosko_producto_tamanos',
                'managed': True,
                'unique_together': {('producto', 'tamano')},
            },
        ),
        migrations.AddField(
            model_name='appkioskoproductos',
            name='tamanos',
            field=models.ManyToManyField(blank=True, related_name='productos', through='catalogo.AppkioskoProductoTamanos', to='catalogo.appkioskotamanos'),
        ),
    ]
