# Generated by Django 5.1.7 on 2025-06-12 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_appkioskotamanos_appkioskoproductos_aplica_tamanos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appkioskomenuproductos',
            options={'managed': False, 'verbose_name': 'Producto del Menú', 'verbose_name_plural': 'Productos del Menú'},
        ),
    ]
