# Generated by Django 5.1.7 on 2025-05-24 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_appkioskocategorias_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appkioskoproductos',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
