# Generated by Django 5.1.7 on 2025-06-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_appkioskomenuproductos_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appkioskomenuproductos',
            table=None,
        ),
    ]
