# Generated by Django 5.1.7 on 2025-05-24 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_appkioskoproductos_options'),
        ('comun', '0003_appkioskoestados_nombre_and_more'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskoproductos',
            name='imagenProductoUrl',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
