# Generated by Django 5.1.7 on 2025-05-25 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_appkioskoproductos_categoria_and_more'),
        ('comun', '0003_appkioskoestados_nombre_and_more'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appkioskocategorias',
            options={'managed': True, 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='appkioskoproductos',
            options={'managed': True, 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        # migrations.AddField(
        #     model_name='appkioskoproductos',
        #     name='categoria',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.appkioskocategorias'),
        # ),
        # migrations.AddField(
        #     model_name='appkioskoproductos',
        #     name='estado',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.appkioskoestados'),
        # ),
        # migrations.AddField(
        #     model_name='appkioskoproductos',
        #     name='promocion',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.appkioskopromociones'),
        # ),
        migrations.AlterField(
            model_name='appkioskoproductos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appkioskoproductos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='AppkioskoIngredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('imagen_ingredienteUrl', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.appkioskoestados')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'db_table': 'appkiosko_ingredientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoProductoingredientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_base', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.appkioskoingredientes')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.appkioskoproductos')),
            ],
            options={
                'verbose_name': 'Ingrediente del Producto',
                'verbose_name_plural': 'Ingredientes del Producto',
                'db_table': 'appkiosko_productos_ingredientes',
                'managed': True,
                'unique_together': {('producto', 'ingrediente')},
            },
        ),
        migrations.AddField(
            model_name='appkioskoproductos',
            name='ingredientes',
            field=models.ManyToManyField(blank=True, related_name='productos', through='catalogo.AppkioskoProductoingredientes', to='catalogo.appkioskoingredientes'),
        ),
        migrations.RunSQL(
            "ALTER TABLE appkiosko_ingredientes MODIFY COLUMN estado_id INT(11) NULL;",
            reverse_sql="ALTER TABLE appkiosko_ingredientes MODIFY COLUMN estado_id BIGINT(20) NULL;"
        ),
        migrations.RunSQL(
            """
            ALTER TABLE appkiosko_ingredientes MODIFY COLUMN estado_id INT(11) NULL;
            ALTER TABLE appkiosko_productos_ingredientes MODIFY COLUMN producto_id INT(11) NOT NULL;
            ALTER TABLE appkiosko_productos_ingredientes MODIFY COLUMN ingrediente_id INT(11) NOT NULL;
            """,
            reverse_sql="""
            ALTER TABLE appkiosko_ingredientes MODIFY COLUMN estado_id BIGINT(20) NULL;
            ALTER TABLE appkiosko_productos_ingredientes MODIFY COLUMN producto_id BIGINT(20) NOT NULL;
            ALTER TABLE appkiosko_productos_ingredientes MODIFY COLUMN ingrediente_id BIGINT(20) NOT NULL;
            """
        ),
    ]
