# Generated by Django 5.1.7 on 2025-06-12 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_add_tamano_to_menuproductos'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appkioskomenuproductos',
            table='appkiosko_menuproductos',
        ),
    ]
