# Generated by Django 5.1.7 on 2025-05-28 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_add_personalizaciones'),
        ('comun', '0004_add_personalizaciones'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskocategorias',
            name='ImagenCategoriaURL',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appkioskoproductos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.appkioskocategorias'),
        ),
        migrations.AddField(
            model_name='appkioskoproductos',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.appkioskoestados'),
        ),
        migrations.AddField(
            model_name='appkioskoproductos',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.appkioskopromociones'),
        ),
    ]
