# Generated by Django 5.1.7 on 2025-06-12 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_add_tamano_column'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appkioskomenuproductos',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appkioskomenuproductos',
            name='tamano',
            field=models.ForeignKey(blank=True, help_text='Tamaño específico del producto en este menú (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.appkioskotamanos'),
        ),
    ]
