# Generated by Django 5.1.7 on 2025-06-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_alter_appkioskomenuproductos_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskoingredientes',
            name='stock',
            field=models.IntegerField(default=0, help_text='Cantidad disponible en inventario'),
        ),
        migrations.AddField(
            model_name='appkioskoingredientes',
            name='stock_minimo',
            field=models.IntegerField(default=5, help_text='Cantidad mínima de alerta de stock'),
        ),
        migrations.AddField(
            model_name='appkioskoingredientes',
            name='unidad_medida',
            field=models.CharField(default='unidades', help_text='Ej: unidades, gramos, litros, etc.', max_length=20),
        ),
    ]
