# Generated by Django 5.1.7 on 2025-06-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_appkioskoingredientes_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskoingredientes',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del ingrediente', null=True, upload_to='ingredientes/'),
        ),
    ]
