# Generated by Django 5.1.7 on 2025-06-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_appkioskoingredientes_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskoproductosingredientes',
            name='cantidad',
            field=models.IntegerField(default=1, help_text='Cantidad de este ingrediente en el producto (ej: doble carne = 2)'),
        ),
    ]
