# Generated by Django 5.1.7 on 2025-06-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_appkioskoproductosingredientes_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appkioskoingredientes',
            name='categoria_producto',
            field=models.CharField(help_text='Categoría del producto para el cual aplica este ingrediente', max_length=50),
        ),
        migrations.AlterField(
            model_name='appkioskoingredientes',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appkioskoingredientes',
            name='precio_adicional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
