# Generated by Django 5.1.7 on 2025-05-30 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppkioskoEstados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Estado Desconocido', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('is_inactive', models.BooleanField(default=False)),
                ('is_order_preparing', models.BooleanField(default=False)),
                ('is_order_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'appkiosko_estados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=500)),
                ('categoria_imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('entidad_relacionada_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'db_table': 'appkiosko_imagen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoTipopago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pago',
                'db_table': 'appkiosko_tipopago',
                'managed': True,
            },
        ),
    ]
