# Generated by Django 5.1.7 on 2025-05-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppkioskoEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField()),
                ('is_eliminated', models.IntegerField()),
                ('is_inactive', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado Kiosko',
                'verbose_name_plural': 'Estados Kiosko',
                'db_table': 'appkiosko_estados',
                'managed': False,
            },
        ),
    ]
