# Generated by Django 5.1.7 on 2025-05-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appkioskoimagen',
            name='categoria_imagen',
            field=models.CharField(blank=True, choices=[('productos', 'Productos'), ('ingredientes', 'Ingredientes'), ('menu', 'Menú'), ('publicidad', 'Publicidad'), ('categorias', 'Categorías')], max_length=100, null=True),
        ),
    ]
