# Generated by Django 5.1.7 on 2025-05-24 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appkioskoestados',
            options={'ordering': ['nombre'], 'verbose_name': 'Estado Kiosko', 'verbose_name_plural': 'Estados Kiosko'},
        ),
    ]
