# Generated by Django 5.1.7 on 2025-05-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0002_alter_appkioskoestados_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskoestados',
            name='nombre',
            field=models.CharField(default='Estado Desconocido', help_text='Nombre descriptivo del estado (ej: Disponible, Agotado)', max_length=100),
        ),
        migrations.AlterField(
            model_name='appkioskoestados',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appkioskoestados',
            name='is_active',
            field=models.BooleanField(default=False, help_text='¿Este estado implica que la entidad está activa/operativa?'),
        ),
        migrations.AlterField(
            model_name='appkioskoestados',
            name='is_eliminated',
            field=models.BooleanField(default=False, help_text='¿Este estado implica que la entidad está lógicamente eliminada?'),
        ),
        migrations.AlterField(
            model_name='appkioskoestados',
            name='is_inactive',
            field=models.BooleanField(default=False, help_text='¿Este estado implica que la entidad está temporalmente inactiva pero no eliminada?'),
        ),
        migrations.AlterField(
            model_name='appkioskoestados',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
