# Generated by Django 5.1.7 on 2025-06-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0002_alter_appkioskoimagen_categoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appkioskoimagen',
            name='categoria_imagen',
            field=models.CharField(blank=True, choices=[('productos', 'Productos'), ('ingredientes', 'Ingredientes'), ('menu', 'Menú'), ('publicidad', 'Publicidad'), ('categorias', 'Categorías'), ('establecimientos', 'Establecimientos')], max_length=100, null=True),
        ),
    ]
