# Generated by Django 5.1.7 on 2025-05-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0003_appkioskoestados_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appkioskoestados',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
