# Generated by Django 5.1.7 on 2025-06-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0003_alter_appkioskoimagen_categoria_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppkioskoIva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, help_text='Ejemplo: 15.00 para IVA del 15%', max_digits=5, verbose_name='Porcentaje de IVA')),
                ('activo', models.BooleanField(default=True, help_text='Solo puede haber un IVA activo a la vez', verbose_name='Activo')),
                ('fecha_vigencia', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Vigencia')),
                ('observaciones', models.TextField(blank=True, help_text='Notas sobre el cambio de IVA', null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de IVA',
                'verbose_name_plural': 'Configuraciones de IVA',
                'db_table': 'appkiosko_iva',
                'ordering': ['-fecha_vigencia'],
                'managed': True,
            },
        ),
    ]
