# Generated by Django 5.1.7 on 2025-06-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0004_appkioskoiva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appkioskoiva',
            options={'managed': True, 'verbose_name': 'Configuración de IVA', 'verbose_name_plural': 'Configuraciones de IVA'},
        ),
        migrations.RemoveField(
            model_name='appkioskoiva',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='appkioskoiva',
            name='fecha_vigencia',
        ),
        migrations.RemoveField(
            model_name='appkioskoiva',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='appkioskoiva',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='appkioskoiva',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='appkioskoiva',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje de IVA'),
        ),
    ]
