# Generated by Django 5.1.7 on 2025-08-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0005_alter_appkioskoiva_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appkioskoiva',
            options={'managed': True, 'verbose_name': 'Configuración Empresarial', 'verbose_name_plural': 'Configuración Empresarial'},
        ),
        migrations.AddField(
            model_name='appkioskoiva',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='appkioskoiva',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='appkioskoiva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appkioskoiva',
            name='direccion',
            field=models.TextField(blank=True, help_text='Dirección completa del establecimiento', null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='appkioskoiva',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='appkioskoiva',
            name='nombre_comercial',
            field=models.CharField(blank=True, help_text='Nombre comercial del establecimiento', max_length=300, null=True, verbose_name='Nombre Comercial'),
        ),
        migrations.AddField(
            model_name='appkioskoiva',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='appkioskoiva',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre legal de la empresa', max_length=300, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='appkioskoiva',
            name='ruc',
            field=models.CharField(blank=True, help_text='RUC de la empresa (13 dígitos)', max_length=13, null=True, verbose_name='RUC'),
        ),
        migrations.AddField(
            model_name='appkioskoiva',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='appkioskoiva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
