# Generated by Django 5.1.7 on 2025-05-30 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppkioskoEstablecimientos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo_establecimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.appkioskoestados')),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'db_table': 'appkiosko_establecimientos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPantallascocina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimientos.appkioskoestablecimientos')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.appkioskoestados')),
            ],
            options={
                'verbose_name': 'Pantalla de Cocina',
                'verbose_name_plural': 'Pantallas de Cocina',
                'db_table': 'appkiosko_pantallascocina',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoKioskostouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimientos.appkioskoestablecimientos')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.appkioskoestados')),
                ('pantallas_cocina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='establecimientos.appkioskopantallascocina')),
            ],
            options={
                'verbose_name': 'Kiosko Touch',
                'verbose_name_plural': 'Kioskos Touch',
                'db_table': 'appkiosko_kioskostouch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoEstablecimientosusuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_trabajo', models.DateTimeField()),
                ('fecha_fin_trabajo', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.appkioskoempleados')),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='establecimientos.appkioskoestablecimientos')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.appkioskoestados')),
            ],
            options={
                'verbose_name': 'Establecimiento Usuario',
                'verbose_name_plural': 'Establecimientos Usuarios',
                'db_table': 'appkiosko_establecimientosusuarios',
                'managed': True,
                'unique_together': {('establecimiento', 'empleado', 'fecha_inicio_trabajo')},
            },
        ),
    ]
