# Generated by Django 5.1.7 on 2025-05-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppkioskoEstablecimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo_establecimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, db_column='image_URL', max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Establecimiento',
                'verbose_name_plural': 'Establecimientos',
                'db_table': 'appkiosko_establecimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoEstablecimientosusuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_iniciotrabajo', models.DateTimeField(db_column='fecha_inicioTrabajo')),
                ('fecha_fintrabajo', models.DateTimeField(blank=True, db_column='fecha_finTrabajo', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Empleado por Establecimiento',
                'verbose_name_plural': 'Empleados por Establecimiento',
                'db_table': 'appkiosko_establecimientosusuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoKioskostouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kiosko Touch',
                'verbose_name_plural': 'Kioskos Touch',
                'db_table': 'appkiosko_kioskostouch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPantallascocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Pantalla de Cocina',
                'verbose_name_plural': 'Pantallas de Cocina',
                'db_table': 'appkiosko_pantallascocina',
                'managed': False,
            },
        ),
    ]
