# Generated by Django 5.1.7 on 2025-06-06 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
        ('usuarios', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskoestablecimientos',
            name='cargo_asignado',
            field=models.CharField(blank=True, help_text='Cargo del empleado responsable (se llena automáticamente)', max_length=100, null=True, verbose_name='Cargo del Responsable'),
        ),
        migrations.AddField(
            model_name='appkioskoestablecimientos',
            name='ciudad',
            field=models.CharField(default='No especificada', help_text='Ciudad donde se encuentra el establecimiento', max_length=50, verbose_name='Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appkioskoestablecimientos',
            name='provincia',
            field=models.CharField(default='No especificada', help_text='Provincia donde se encuentra el establecimiento', max_length=50, verbose_name='Provincia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appkioskoestablecimientos',
            name='responsable_asignado',
            field=models.ForeignKey(blank=True, help_text='Empleado responsable del establecimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establecimientos_responsable', to='usuarios.appkioskoempleados', verbose_name='Responsable Asignado'),
        ),
    ]
