# Generated by Django 5.1.7 on 2025-06-07 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0002_alter_appkioskoimagen_categoria_imagen'),
        ('establecimientos', '0002_appkioskoestablecimientos_cargo_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskoestablecimientos',
            name='imagen',
            field=models.ForeignKey(blank=True, help_text='Selecciona una imagen para el establecimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='comun.appkioskoimagen', verbose_name='Imagen del Establecimiento'),
        ),
    ]
