# Generated by Django 5.1.7 on 2025-06-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0003_appkioskoestablecimientos_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appkioskokioskostouch',
            name='pantallas_cocina',
        ),
        migrations.AddField(
            model_name='appkioskopantallascocina',
            name='kioskos_asociados',
            field=models.ManyToManyField(blank=True, related_name='pantallas_asociadas', to='establecimientos.appkioskokioskostouch'),
        ),
    ]
