# Generated by Django 5.1.7 on 2025-04-01 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppkioskoCategorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_creacioncupon', models.DateTimeField(blank=True, db_column='fecha_creacionCupon', null=True)),
                ('fecha_fincupon', models.DateTimeField(blank=True, db_column='fecha_finCupon', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_cupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoFacturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('cedula_cliente', models.CharField(blank=True, max_length=10, null=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoEstablecimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo_establecimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('image_url', models.CharField(blank=True, db_column='image_URL', max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_establecimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoEstados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField()),
                ('is_eliminated', models.IntegerField()),
                ('is_inactive', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_estados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=500)),
                ('categoria_imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_referencial_imagen', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_imagen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoKioskostouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_kioskostouch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_menu', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_menus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPantallascocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_pantallascocina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('tipo_entrega', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_mesa', models.IntegerField(blank=True, null=True)),
                ('valor_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('is_facturado', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_pedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPedidosessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_iniciopedido', models.DateTimeField(db_column='fecha_inicioPedido')),
                ('fecha_finpedido', models.DateTimeField(blank=True, db_column='fecha_finPedido', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_pedidosessions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPromociones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_descuento', models.IntegerField()),
                ('fecha_iniciopromo', models.DateTimeField(db_column='fecha_inicioPromo')),
                ('fecha_finpromo', models.DateTimeField(blank=True, db_column='fecha_finPromo', null=True)),
                ('tipo_promocion', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_promocional', models.CharField(blank=True, max_length=50, null=True)),
                ('limite_uso_usuario', models.IntegerField(blank=True, null=True)),
                ('aplicable_a', models.CharField(blank=True, max_length=100, null=True)),
                ('limite_uso_total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_promociones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPublicidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_publicidad', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_or_video_url', models.CharField(blank=True, db_column='imagen_or_video_URL', max_length=500, null=True)),
                ('fecha_iniciopublicidad', models.DateTimeField(blank=True, db_column='fecha_inicioPublicidad', null=True)),
                ('fecha_finpublicidad', models.DateTimeField(blank=True, db_column='fecha_finPublicidad', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_publicidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoTipopago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_tipopago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=500)),
                ('duracion', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPromocioncategoria',
            fields=[
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.appkioskocategorias')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_promocioncategoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoDetallefacturaproducto',
            fields=[
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.appkioskofacturas')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.DecimalField(db_column='IVA', decimal_places=2, max_digits=5)),
                ('descuento', models.DecimalField(blank=True, db_column='DESCUENTO', decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emisionfactura', models.DateTimeField(db_column='fecha_emisionFactura')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_detallefacturaproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoEstablecimientosusuarios',
            fields=[
                ('establecimiento', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.appkioskoestablecimientos')),
                ('fecha_iniciotrabajo', models.DateTimeField(db_column='fecha_inicioTrabajo')),
                ('fecha_fintrabajo', models.DateTimeField(blank=True, db_column='fecha_finTrabajo', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_establecimientosusuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPublicidadestablecimiento',
            fields=[
                ('establecimiento', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.appkioskoestablecimientos')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_publicidadestablecimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPublicidadkioskotouch',
            fields=[
                ('kioskotouch', models.OneToOneField(db_column='kioskoTouch_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.appkioskokioskostouch')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_publicidadkioskotouch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoMenuproductos',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.appkioskoproductos')),
                ('cantidad', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_menuproductos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPromocionproductos',
            fields=[
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.appkioskoproductos')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_promocionproductos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPromocionmenu',
            fields=[
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.appkioskomenus')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_promocionmenu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppkioskoPedidosproductos',
            fields=[
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='main.appkioskopedidos')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'appkiosko_pedidosproductos',
                'managed': False,
            },
        ),
    ]
