# Generated by Django 5.1.7 on 2025-05-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appkioskoclientes',
            options={'managed': True, 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
