# Generated by Django 5.1.7 on 2025-05-28 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_campos_empleados_nuevos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appkioskoempleados',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appkioskoempleados',
            name='turno_trabajo',
            field=models.CharField(
                blank=True,
                choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')],
                max_length=20,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='appkioskoempleados',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appkioskoempleados',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appkioskoempleados',
            name='sexo',
            field=models.CharField(
                blank=True,
                choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')],
                max_length=50,
                null=True
            ),
        ),
    ]
