# Generated by Django 5.1.7 on 2025-05-28 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_agregar_campos_empleados2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appkioskoclientes',
            options={'managed': False, 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='appkioskoempleados',
            options={'managed': True, 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
