name: QualityCheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'Frontend/package-lock.json'
        
    - name: Install dependencies
      working-directory: Frontend
      run: npm ci
      
    - name: Run linting 
      working-directory: Frontend
      run: npx ng lint
      
    - name: Run tests
      working-directory: Frontend
      run: npx ng test --watch=false --browsers=ChromeHeadless --include=src/app/testing/auth-permission.integration.spec.ts --include=src/app/testing/pedido-flow.integration.spec.ts --include=src/app/testing/admin-navigation.integration.spec.ts --include=src/app/testing/cliente-menu-integration.spec.ts --include=src/app/testing/admin-product-creation.integration.spec.ts --include=src/app/testing/service-integration.integration.spec.ts
      
    - name: Build project
      working-directory: Frontend
      run: npm run build