name: QualityCheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'Frontend/package-lock.json'
    - name: Install dependencies
      working-directory: Frontend
      run: npm ci
    - name: Run ESLint
      working-directory: Frontend
      run: npm run lint || true

  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'Frontend/package-lock.json'
    - name: Install dependencies
      working-directory: Frontend
      run: npm ci
    - name: Run tests
      working-directory: Frontend
      run: npx ng test --watch=false --browsers=ChromeHeadless --include=src/app/testing/auth-permission.integration.spec.ts --include=src/app/testing/pedido-flow.integration.spec.ts --include=src/app/testing/admin-navigation.integration.spec.ts --include=src/app/testing/cliente-menu-integration.spec.ts --include=src/app/testing/admin-product-creation.integration.spec.ts --include=src/app/testing/service-integration.integration.spec.ts

  building:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'Frontend/package-lock.json'
    - name: Install dependencies
      working-directory: Frontend
      run: npm ci
    - name: Build application
      working-directory: Frontend
      run: npm run build

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Necesario para SonarCloud
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'Frontend/package-lock.json'
    - name: Install dependencies
      working-directory: Frontend
      run: npm ci
    - name: Run tests with coverage
      working-directory: Frontend
      run: ng test --watch=false --browsers=ChromeHeadless --code-coverage
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: Frontend
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
